76 add google colab notebook demo
mozilla-ai/document-to-podcast pull request #77
Opened 2024-12-27 10:34 UTC by daavoo

2024-12-27 10:47 UTC, daavoo commented on demo/notebook.ipynb
Need to update the installation cell after #75 is merged

2024-12-30 11:41 UTC, Kostis-S-Z commented on README.md
> +
I would suggest we put this badge together with the other badges on the top of the README.

Also we should add it as an option in the #Quick-start section

2024-12-30 12:04 UTC, Kostis-S-Z commented on docs/getting-started.md
> -```
Is there a reason why this should be removed?

2025-01-09 13:18 UTC, stefanfrench requested changes
@daavoo - Tested this and it worked well on the T4 GPU.

The addition of the content tabs in the Docs looks great!

One minor change I think we should implement - in both the Docs and the Colab Notebook, I think we should be explicit about the user ensuring they change the Colab runtime to a GPU - as it defaults to a CPU, and if they dont change it, it will break. Something like: 
"This notebook requires a GPU runtime to function correctly. Using a CPU runtime will result in errors.

How to Switch to GPU:
	1.	Go to Runtime > Change runtime type in the top menu.
	2.	Set Hardware accelerator to GPU.
	3.	Click Save.
"

2025-01-13 09:42 UTC, stefanfrench approved these changes
@daavoo - thanks for adding the GPU check, works great! Approved.

2025-01-13 10:23 UTC, merged